export const authConstants = {
    LOGIN_REEQUEST: 'LOGIN_REEQUEST',
    LOGIN_FAILUR: 'LOGIN_FAILUR',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILUR: 'LOGOUT_FAILUR',
};

export const userConstants = {
    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILURE: 'USER_REQUEST_FAILURE',
    GET_USER_ADDRESS_REQUEST: "GET_USER_ADDRESS_REQUEST",
    GET_USER_ADDRESS_SUCCESS: "GET_USER_ADDRESS_SUCCESS",
    GET_USER_ADDRESS_FAILURE: "GET_USER_ADDRESS_FAILURE",
    ADD_USER_ADDRESS_REQUEST: "ADD_USER_ADDRESS_REQUEST",
    ADD_USER_ADDRESS_SUCCESS: "ADD_USER_ADDRESS_SUCCESS",
    ADD_USER_ADDRESS_FAILURE: "ADD_USER_ADDRESS_FAILURE",
    ADD_USER_ORDER_REQUEST: "ADD_USER_ORDER_REQUEST",
    ADD_USER_ORDER_SUCCESS: "ADD_USER_ORDER_SUCCESS",
    ADD_USER_ORDER_FAILURE: "ADD_USER_ORDER_FAILURE",
  
    GET_USER_ORDER_REQUEST: "GET_USER_ORDER_REQUEST",
    GET_USER_ORDER_SUCCESS: "GET_USER_ORDER_SUCCESS",
    GET_USER_ORDER_FAILURE: "GET_USER_ORDER_FAILURE",
  
    GET_USER_ORDER_DETAILS_REQUEST: "GET_USER_ORDER_DETAILS_REQUEST",
    GET_USER_ORDER_DETAILS_SUCCESS: "GET_USER_ORDER_DETAILS_SUCCESS",
    GET_USER_ORDER_DETAILS_FAILURE: "GET_USER_ORDER_DETAILS_FAILURE",
};

export const categoryConstants = {
    GET_ALL_CATEGORY_REQUEST: 'GET_ALL_CATEGORY_REQUEST',
    GET_ALL_CATEGORY_SUCCESS: 'GET_ALL_CATEGORY_SUCCESS',
    GET_ALL_CATEGORY_FAILURE: 'GET_ALL_CATEGORY_FAILURE',
};

export const productConstants = {
    POST_PRODUCT_REQUEST: 'POST_PRODUCT_REQUEST',
    GET_PRODUCT_REQUEST: 'GET_PRODUCT_REQUEST',
    POST_PRODUCT_SUCCESS: 'POST_PRODUCT_SUCCESS',
    GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
    POST_PRODUCT_FAILURE: 'POST_PRODUCT_FAILURE',
    GET_PRODUCT_FAILURE: 'GET_PRODUCT_FAILURE',
    GET_PRODUCT_BY_CATEGORY_REQUEST: 'GET_PRODUCT_BY_CATEGORY_REQUEST',
    GET_PRODUCT_BY_CATEGORY_SUCCESS: 'GET_PRODUCT_BY_CATEGORY_SUCCESS',
    GET_PRODUCT_BY_CATEGORY_FAILURE: 'GET_PRODUCT_BY_CATEGORY_FAILURE',
    GET_PRODUCT_BY_PAGE_SUCCESS: 'GET_PRODUCT_BY_PAGE_SUCCESS',
    GET_PRODUCT_BY_PAGE_REQUEST: 'GET_PRODUCT_BY_PAGE_REQUEST',
    GET_PRODUCT_BY_PAGE_FAILURE: 'GET_PRODUCT_BY_PAGE_FAILURE',
    GET_PRODUCT_SINGLE_SUCCESS: 'GET_PRODUCT_SINGLE_SUCCESS',
    GET_PRODUCT_SINGLE_REQUEST: 'GET_PRODUCT_SINGLE_REQUEST',
    GET_PRODUCT_SINGLE_FAILURE: 'GET_PRODUCT_SINGLE_FAILURE',
};

export const initialDataConstants = {
    GET_ALL_INITIALDATA_REQUEST: 'GET_ALL_INITIALDATA_REQUEST',
    GET_ALL_INITIALDATA_SUCCESS: 'GET_ALL_INITIALDATA_SUCCESS',
    GET_ALL_INITIALDATA_FAILURE: 'GET_ALL_INITIALDATA_FAILURE',
};

export const cartConstants = {
    ADD_TO_CART_REQUEST: 'ADD_TO_CART_REQUEST',
    ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
    ADD_TO_CART_FAILURE: 'ADD_TO_CART_FAILURE',
    RESET_CART: 'RESET_CART',

    REMOVE_CART_ITEM_REQUEST: 'REMOVE_CART_ITEM_REQUEST',
    REMOVE_CART_ITEM_SUCCESS: 'REMOVE_CART_ITEM_SUCCESS',
    REMOVE_CART_ITEM_FAILURE: 'REMOVE_CART_ITEM_FAILURE',
};