export const authConstants = {
    LOGIN_REEQUEST: 'LOGIN_REEQUEST',
    LOGIN_FAILUR: 'LOGIN_FAILUR',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILUR: 'LOGOUT_FAILUR',
};

export const userConstants = {
    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILURE: 'USER_REQUEST_FAILURE',
};

export const categoryConstants = {
    GET_ALL_CATEGORY_REQUEST: 'GET_ALL_CATEGORY_REQUEST',
    GET_ALL_CATEGORY_SUCCESS: 'GET_ALL_CATEGORY_SUCCESS',
    GET_ALL_CATEGORY_FAILURE: 'GET_ALL_CATEGORY_FAILURE',
    POST_CATEGORY_REQUEST: 'POST_CATEGORY_REQUEST',
    POST_CATEGORY_SUCCESS: 'POST_CATEGORY_SUCCESS',
    POST_CATEGORY_FAILURE: 'POST_CATEGORY_FAILURE',
};

export const productConstants = {
    POST_PRODUCT_REQUEST: 'POST_PRODUCT_REQUEST',
    GET_PRODUCT_REQUEST: 'GET_PRODUCT_REQUEST',
    POST_PRODUCT_SUCCESS: 'POST_PRODUCT_SUCCESS',
    GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
    POST_PRODUCT_FAILURE: 'POST_PRODUCT_FAILURE',
    GET_PRODUCT_FAILURE: 'GET_PRODUCT_FAILURE',
};

export const initialDataConstants = {
    GET_ALL_INITIALDATA_REQUEST: 'GET_ALL_INITIALDATA_REQUEST',
    GET_ALL_INITIALDATA_SUCCESS: 'GET_ALL_INITIALDATA_SUCCESS',
    GET_ALL_INITIALDATA_FAILURE: 'GET_ALL_INITIALDATA_FAILURE',
};
